// Presentation only. Recipe source, ingredients, instructions, and dish-image mappings stay in their original files.
export function renderHome({photo, atmosphere, card, lanes, laneCount, cap, arrow}) {
  return `<section class="masthead" aria-labelledby="welcome-title">
    <div class="masthead-image">${atmosphere('seoul-table-atmosphere',true)}</div>
    <div class="masthead-content wrap"><p class="eyebrow">고추장 &nbsp; / &nbsp; The Seoul Table</p><h1 id="welcome-title">A little heat.<br>A <em>deeper</em> story.</h1><p>Korean roots. An open kitchen.<br>Recipes for a generous table.</p><a class="button light" href="/recipes/">Find your next dish ${arrow}</a></div>
    <div class="masthead-caption wrap"><span>A collection for curious cooks</span><a href="#the-collection">Discover the table <span aria-hidden="true">↓</span></a></div>
  </section>
  <section class="table-intro wrap" id="the-collection"><p class="eyebrow">The pleasure of cooking. The art of sharing.</p><p class="intro-statement">Familiar flavors.<br><em>Unexpected possibilities.</em></p><p>Korean classics, modern favorites, and new ways with gochujang. Fourteen recipes. Three paths. A place for everyone.</p></section>
  <section class="chapter-strip wrap" aria-label="Explore recipe collections">${lanes.map(l=>`<a href="/recipes/?lane=${l.id}"><span class="chapter-num">${l.num}</span><div><h2>${cap(l.id)} <sup>${laneCount(l.id)}</sup></h2><p>${l.text}</p></div>${arrow}</a>`).join('')}</section>
  <section class="section wrap home-selection"><div class="section-heading"><div><p class="eyebrow">01 / The collection</p><h2>Something for <em>your table.</em></h2></div><a class="text-link" href="/recipes/">Explore all 14 recipes ${arrow}</a></div><div class="recipe-grid editorial-grid">${['dolsot-bibimbap','rose-tteokbokki','yangnyeom-fried-chicken'].map((s,i)=>card(s,`0${i+1}`)).join('')}</div></section>
  <section class="centerpiece wrap"><a class="centerpiece-photo" href="/recipes/gochujang-glazed-galbi-short-ribs/" aria-label="Gochujang-Glazed Galbi">${photo('gochujang-glazed-galbi-short-ribs')}</a><div class="centerpiece-copy"><p class="eyebrow">02 / The Sunday centerpiece</p><h2>Slow down.<br><em>Gather around.</em></h2><p>Deeply glazed galbi, a little patience, and a table worth lingering at. Some dishes deserve the center.</p><a class="text-link" href="/recipes/gochujang-glazed-galbi-short-ribs/">Make the gochujang galbi ${arrow}</a><span class="centerpiece-note">Modern Korean · For the whole table</span></div></section>
  <section class="story-panel"><div class="wrap story-inner"><figure class="story-photo">${atmosphere('seoul-table-jar')}<figcaption>고추장 / A little goes a long way.</figcaption></figure><div class="story-copy"><p class="eyebrow">03 / The ingredient at our heart</p><h2>A small jar.<br><em>A whole world.</em></h2><p>Sweetness. Depth. A slow-building warmth. Gochujang brings more to a dish than its color suggests.</p><p>Here, the classic sits beside the curious. We make room for both—and tell you when a recipe takes a new direction.</p><a class="text-link" href="/about/">The thinking behind the table ${arrow}</a></div></div></section>
  <section class="section wrap sweet-section"><div class="sweet-copy"><p class="eyebrow">04 / An unexpected ending</p><h2>And a little<br><em>something sweet.</em></h2><p>Dark chocolate. A quiet hum of heat. Some of the most interesting places for gochujang are the ones you haven’t tried yet.</p><a class="text-link" href="/recipes/gochujang-dark-chocolate-tart/">Make the chocolate tart ${arrow}</a><span class="centerpiece-note">Fusion · A different kind of finish</span></div><a class="sweet-photo" href="/recipes/gochujang-dark-chocolate-tart/" aria-label="Gochujang Dark Chocolate Tart">${photo('gochujang-dark-chocolate-tart')}</a></section>
  <section class="table-invitation wrap"><span class="invitation-mark" aria-hidden="true">고추장</span><p class="eyebrow">Good food. A generous table.</p><h2>There’s always room<br>for <em>one more.</em></h2><a class="button dark" href="/recipes/">Find something to cook ${arrow}</a></section>`;
}

export function renderHeader({mark,arrow,searchIcon}) {
  return `<a class="skip-link" href="#main">Skip to content</a><div class="topline"><span>Korean roots. An open kitchen.</span><span>고추장 <span class="topline-divider">/</span> The Seoul Table</span></div><header class="site-header"><a class="brand" href="/" aria-label="Gochujang home">${mark}</a><span class="header-edition">The Seoul Table <span>Volume 01 · Fourteen recipes</span></span><nav aria-label="Main navigation"><a href="/recipes/">The recipes</a><a href="/about/">Our approach</a><button class="search-open icon-button" aria-label="Search recipes">${searchIcon}</button><button class="menu-toggle icon-button" aria-label="Open menu" aria-expanded="false" aria-controls="mobile-menu"><span></span><span></span></button></nav></header><nav id="mobile-menu" class="mobile-menu" aria-label="Mobile navigation" hidden><p class="eyebrow">Find your place at the table</p><a href="/recipes/">The recipes ${arrow}</a><a href="/recipes/?lane=traditional">Traditional <span>01</span></a><a href="/recipes/?lane=modern">Modern <span>02</span></a><a href="/recipes/?lane=fusion">Fusion <span>03</span></a><a href="/recipes/?saved=1">Saved recipes <span data-saved-total>0</span></a><a href="/about/">Our approach ${arrow}</a></nav>`;
}

export function renderFooter({mark,arrow}) {
  return `<footer class="site-footer"><div class="footer-opening"><p class="eyebrow">From our collection to your kitchen</p><p>Cook with curiosity.<br><em>Share with generosity.</em></p><a class="footer-round-link" href="/recipes/" aria-label="Explore all recipes">${arrow}</a></div><div class="footer-top"><div><a class="brand" href="/" aria-label="Gochujang home">${mark}</a><p>Rooted in Korea.<br>Curious about everywhere.</p></div><div><span class="eyebrow">Find your next dish</span><a href="/recipes/">All recipes</a><a href="/recipes/?lane=traditional">Traditional</a><a href="/recipes/?lane=modern">Modern</a><a href="/recipes/?lane=fusion">Fusion</a></div><div><span class="eyebrow">Around the table</span><a href="/about/">Our approach</a><a href="https://kbbqguide.com/">KBBQGuide ${arrow}</a><a href="/recipes/?saved=1">Your saved recipes</a></div></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} Gochujang</span><span>The Seoul Table · 고추장</span><a href="#top">Back to top ↑</a></div></footer>`;
}
